// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.tvvnc.tv_vnc.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object TvApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class CommandKind(val raw: Int) {
  KEY(0),
  KEY_DOWN(1),
  KEY_UP(2),
  SONY(3),
  TEXT(4),
  INPUT(5),
  APP(6),
  POWER_ON(7),
  POWER_OFF(8),
  POWER_TOGGLE(9),
  MUTE(10),
  UNMUTE(11),
  VOLUME(12),
  REBOOT(13),
  PASTE(14);

  companion object {
    fun ofRaw(raw: Int): CommandKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class Availability(val raw: Int) {
  UNKNOWN(0),
  ADVERTISED(1),
  NEEDS_SETUP(2),
  PERMISSION_REQUIRED(3),
  READY(4),
  UNAVAILABLE(5),
  UNSUPPORTED(6);

  companion object {
    fun ofRaw(raw: Int): Availability? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class Delivery(val raw: Int) {
  NOT_SENT(0),
  REJECTED(1),
  SENT(2),
  CONFIRMED(3),
  UNKNOWN(4),
  QUEUED(5);

  companion object {
    fun ofRaw(raw: Int): Delivery? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MacroAction(val raw: Int) {
  WAKE(0),
  HOME(1),
  INPUT(2),
  APP(3),
  WAIT_FOR_TV(4),
  KEY(5),
  SONY(6);

  companion object {
    fun ofRaw(raw: Int): MacroAction? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MacroStep (
  val action: MacroAction,
  val value: String? = null,
  val timeoutSeconds: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MacroStep {
      val action = pigeonVar_list[0] as MacroAction
      val value = pigeonVar_list[1] as String?
      val timeoutSeconds = pigeonVar_list[2] as Long
      return MacroStep(action, value, timeoutSeconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      action,
      value,
      timeoutSeconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MacroStep
    return TvApiPigeonUtils.deepEquals(this.action, other.action) && TvApiPigeonUtils.deepEquals(this.value, other.value) && TvApiPigeonUtils.deepEquals(this.timeoutSeconds, other.timeoutSeconds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.action)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.value)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.timeoutSeconds)
    return result
  }
  override fun toString(): String {
    return "MacroStep(action=$action, value=$value, timeoutSeconds=$timeoutSeconds)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TvMacro (
  val id: String,
  val name: String,
  val steps: List<MacroStep>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TvMacro {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val steps = pigeonVar_list[2] as List<MacroStep>
      return TvMacro(id, name, steps)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      steps,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TvMacro
    return TvApiPigeonUtils.deepEquals(this.id, other.id) && TvApiPigeonUtils.deepEquals(this.name, other.name) && TvApiPigeonUtils.deepEquals(this.steps, other.steps)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.id)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.name)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.steps)
    return result
  }
  override fun toString(): String {
    return "TvMacro(id=$id, name=$name, steps=$steps)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TvProfile (
  val id: String,
  val name: String,
  val host: String,
  val vncPort: Long,
  val remotePort: Long,
  val pairingPort: Long,
  val mac: String? = null,
  val hasVncPassword: Boolean,
  val hasSonyKey: Boolean,
  val paired: Boolean,
  val layout: List<String>,
  val favorites: List<String>,
  val recents: List<String>,
  val macros: List<TvMacro>,
  val droidVnc: Boolean,
  val pointerVerified: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TvProfile {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val host = pigeonVar_list[2] as String
      val vncPort = pigeonVar_list[3] as Long
      val remotePort = pigeonVar_list[4] as Long
      val pairingPort = pigeonVar_list[5] as Long
      val mac = pigeonVar_list[6] as String?
      val hasVncPassword = pigeonVar_list[7] as Boolean
      val hasSonyKey = pigeonVar_list[8] as Boolean
      val paired = pigeonVar_list[9] as Boolean
      val layout = pigeonVar_list[10] as List<String>
      val favorites = pigeonVar_list[11] as List<String>
      val recents = pigeonVar_list[12] as List<String>
      val macros = pigeonVar_list[13] as List<TvMacro>
      val droidVnc = pigeonVar_list[14] as Boolean
      val pointerVerified = pigeonVar_list[15] as Boolean
      return TvProfile(id, name, host, vncPort, remotePort, pairingPort, mac, hasVncPassword, hasSonyKey, paired, layout, favorites, recents, macros, droidVnc, pointerVerified)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      host,
      vncPort,
      remotePort,
      pairingPort,
      mac,
      hasVncPassword,
      hasSonyKey,
      paired,
      layout,
      favorites,
      recents,
      macros,
      droidVnc,
      pointerVerified,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TvProfile
    return TvApiPigeonUtils.deepEquals(this.id, other.id) && TvApiPigeonUtils.deepEquals(this.name, other.name) && TvApiPigeonUtils.deepEquals(this.host, other.host) && TvApiPigeonUtils.deepEquals(this.vncPort, other.vncPort) && TvApiPigeonUtils.deepEquals(this.remotePort, other.remotePort) && TvApiPigeonUtils.deepEquals(this.pairingPort, other.pairingPort) && TvApiPigeonUtils.deepEquals(this.mac, other.mac) && TvApiPigeonUtils.deepEquals(this.hasVncPassword, other.hasVncPassword) && TvApiPigeonUtils.deepEquals(this.hasSonyKey, other.hasSonyKey) && TvApiPigeonUtils.deepEquals(this.paired, other.paired) && TvApiPigeonUtils.deepEquals(this.layout, other.layout) && TvApiPigeonUtils.deepEquals(this.favorites, other.favorites) && TvApiPigeonUtils.deepEquals(this.recents, other.recents) && TvApiPigeonUtils.deepEquals(this.macros, other.macros) && TvApiPigeonUtils.deepEquals(this.droidVnc, other.droidVnc) && TvApiPigeonUtils.deepEquals(this.pointerVerified, other.pointerVerified)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.id)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.name)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.host)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.vncPort)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.remotePort)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.pairingPort)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.mac)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.hasVncPassword)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.hasSonyKey)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.paired)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.layout)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.favorites)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.recents)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.macros)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.droidVnc)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.pointerVerified)
    return result
  }
  override fun toString(): String {
    return "TvProfile(id=$id, name=$name, host=$host, vncPort=$vncPort, remotePort=$remotePort, pairingPort=$pairingPort, mac=$mac, hasVncPassword=$hasVncPassword, hasSonyKey=$hasSonyKey, paired=$paired, layout=$layout, favorites=$favorites, recents=$recents, macros=$macros, droidVnc=$droidVnc, pointerVerified=$pointerVerified)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TvCredentials (
  val vncPassword: String? = null,
  val sonyKey: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TvCredentials {
      val vncPassword = pigeonVar_list[0] as String?
      val sonyKey = pigeonVar_list[1] as String?
      return TvCredentials(vncPassword, sonyKey)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      vncPassword,
      sonyKey,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TvCredentials
    return TvApiPigeonUtils.deepEquals(this.vncPassword, other.vncPassword) && TvApiPigeonUtils.deepEquals(this.sonyKey, other.sonyKey)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.vncPassword)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.sonyKey)
    return result
  }
  override fun toString(): String {
    return "TvCredentials(vncPassword=$vncPassword, sonyKey=$sonyKey)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DiscoveredTv (
  val name: String,
  val host: String,
  val service: String,
  val port: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DiscoveredTv {
      val name = pigeonVar_list[0] as String
      val host = pigeonVar_list[1] as String
      val service = pigeonVar_list[2] as String
      val port = pigeonVar_list[3] as Long
      return DiscoveredTv(name, host, service, port)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      host,
      service,
      port,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DiscoveredTv
    return TvApiPigeonUtils.deepEquals(this.name, other.name) && TvApiPigeonUtils.deepEquals(this.host, other.host) && TvApiPigeonUtils.deepEquals(this.service, other.service) && TvApiPigeonUtils.deepEquals(this.port, other.port)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.name)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.host)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.service)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.port)
    return result
  }
  override fun toString(): String {
    return "DiscoveredTv(name=$name, host=$host, service=$service, port=$port)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TvButton (
  val id: String,
  val name: String,
  val androidCode: Long? = null,
  val sonyCode: String? = null,
  val canHold: Boolean,
  val disruptive: Boolean,
  val state: Availability
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TvButton {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val androidCode = pigeonVar_list[2] as Long?
      val sonyCode = pigeonVar_list[3] as String?
      val canHold = pigeonVar_list[4] as Boolean
      val disruptive = pigeonVar_list[5] as Boolean
      val state = pigeonVar_list[6] as Availability
      return TvButton(id, name, androidCode, sonyCode, canHold, disruptive, state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      androidCode,
      sonyCode,
      canHold,
      disruptive,
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TvButton
    return TvApiPigeonUtils.deepEquals(this.id, other.id) && TvApiPigeonUtils.deepEquals(this.name, other.name) && TvApiPigeonUtils.deepEquals(this.androidCode, other.androidCode) && TvApiPigeonUtils.deepEquals(this.sonyCode, other.sonyCode) && TvApiPigeonUtils.deepEquals(this.canHold, other.canHold) && TvApiPigeonUtils.deepEquals(this.disruptive, other.disruptive) && TvApiPigeonUtils.deepEquals(this.state, other.state)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.id)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.name)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.androidCode)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.sonyCode)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.canHold)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.disruptive)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.state)
    return result
  }
  override fun toString(): String {
    return "TvButton(id=$id, name=$name, androidCode=$androidCode, sonyCode=$sonyCode, canHold=$canHold, disruptive=$disruptive, state=$state)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TvInput (
  val uri: String,
  val name: String,
  val label: String? = null,
  val connected: Boolean,
  val selected: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TvInput {
      val uri = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val label = pigeonVar_list[2] as String?
      val connected = pigeonVar_list[3] as Boolean
      val selected = pigeonVar_list[4] as Boolean
      return TvInput(uri, name, label, connected, selected)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      name,
      label,
      connected,
      selected,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TvInput
    return TvApiPigeonUtils.deepEquals(this.uri, other.uri) && TvApiPigeonUtils.deepEquals(this.name, other.name) && TvApiPigeonUtils.deepEquals(this.label, other.label) && TvApiPigeonUtils.deepEquals(this.connected, other.connected) && TvApiPigeonUtils.deepEquals(this.selected, other.selected)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.uri)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.name)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.label)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.connected)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.selected)
    return result
  }
  override fun toString(): String {
    return "TvInput(uri=$uri, name=$name, label=$label, connected=$connected, selected=$selected)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TvApplication (
  val id: String,
  val name: String,
  val uri: String,
  val packageName: String? = null,
  val iconBytes: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TvApplication {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val uri = pigeonVar_list[2] as String
      val packageName = pigeonVar_list[3] as String?
      val iconBytes = pigeonVar_list[4] as ByteArray?
      return TvApplication(id, name, uri, packageName, iconBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      uri,
      packageName,
      iconBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TvApplication
    return TvApiPigeonUtils.deepEquals(this.id, other.id) && TvApiPigeonUtils.deepEquals(this.name, other.name) && TvApiPigeonUtils.deepEquals(this.uri, other.uri) && TvApiPigeonUtils.deepEquals(this.packageName, other.packageName) && TvApiPigeonUtils.deepEquals(this.iconBytes, other.iconBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.id)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.name)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.uri)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.packageName)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.iconBytes)
    return result
  }
  override fun toString(): String {
    return "TvApplication(id=$id, name=$name, uri=$uri, packageName=$packageName, iconBytes=${iconBytes?.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CapabilityInfo (
  val id: String,
  val state: Availability,
  val transport: String,
  val observedAt: Long,
  val detail: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CapabilityInfo {
      val id = pigeonVar_list[0] as String
      val state = pigeonVar_list[1] as Availability
      val transport = pigeonVar_list[2] as String
      val observedAt = pigeonVar_list[3] as Long
      val detail = pigeonVar_list[4] as String?
      return CapabilityInfo(id, state, transport, observedAt, detail)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      state,
      transport,
      observedAt,
      detail,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CapabilityInfo
    return TvApiPigeonUtils.deepEquals(this.id, other.id) && TvApiPigeonUtils.deepEquals(this.state, other.state) && TvApiPigeonUtils.deepEquals(this.transport, other.transport) && TvApiPigeonUtils.deepEquals(this.observedAt, other.observedAt) && TvApiPigeonUtils.deepEquals(this.detail, other.detail)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.id)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.state)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.transport)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.observedAt)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.detail)
    return result
  }
  override fun toString(): String {
    return "CapabilityInfo(id=$id, state=$state, transport=$transport, observedAt=$observedAt, detail=$detail)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TransportInfo (
  val id: String,
  val state: Availability,
  val observedAt: Long,
  val errorCode: String? = null,
  val latencyMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TransportInfo {
      val id = pigeonVar_list[0] as String
      val state = pigeonVar_list[1] as Availability
      val observedAt = pigeonVar_list[2] as Long
      val errorCode = pigeonVar_list[3] as String?
      val latencyMs = pigeonVar_list[4] as Long?
      return TransportInfo(id, state, observedAt, errorCode, latencyMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      state,
      observedAt,
      errorCode,
      latencyMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TransportInfo
    return TvApiPigeonUtils.deepEquals(this.id, other.id) && TvApiPigeonUtils.deepEquals(this.state, other.state) && TvApiPigeonUtils.deepEquals(this.observedAt, other.observedAt) && TvApiPigeonUtils.deepEquals(this.errorCode, other.errorCode) && TvApiPigeonUtils.deepEquals(this.latencyMs, other.latencyMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.id)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.state)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.observedAt)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.latencyMs)
    return result
  }
  override fun toString(): String {
    return "TransportInfo(id=$id, state=$state, observedAt=$observedAt, errorCode=$errorCode, latencyMs=$latencyMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EditorInfo (
  val application: String,
  val label: String,
  val text: String,
  val start: Long,
  val end: Long,
  val revision: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EditorInfo {
      val application = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      val text = pigeonVar_list[2] as String
      val start = pigeonVar_list[3] as Long
      val end = pigeonVar_list[4] as Long
      val revision = pigeonVar_list[5] as Long
      return EditorInfo(application, label, text, start, end, revision)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      application,
      label,
      text,
      start,
      end,
      revision,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EditorInfo
    return TvApiPigeonUtils.deepEquals(this.application, other.application) && TvApiPigeonUtils.deepEquals(this.label, other.label) && TvApiPigeonUtils.deepEquals(this.text, other.text) && TvApiPigeonUtils.deepEquals(this.start, other.start) && TvApiPigeonUtils.deepEquals(this.end, other.end) && TvApiPigeonUtils.deepEquals(this.revision, other.revision)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.application)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.label)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.text)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.start)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.end)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.revision)
    return result
  }
  override fun toString(): String {
    return "EditorInfo(application=$application, label=$label, text=$text, start=$start, end=$end, revision=$revision)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ScreenInfo (
  val textureId: Long? = null,
  val width: Long,
  val height: Long,
  val generation: Long,
  val frameAt: Long,
  val connected: Boolean,
  val stale: Boolean,
  val errorCode: String? = null,
  val desktopName: String? = null,
  val securityType: Long? = null,
  val protocolVersion: String? = null,
  val extendedClipboard: Boolean? = null,
  val hidden: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScreenInfo {
      val textureId = pigeonVar_list[0] as Long?
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      val generation = pigeonVar_list[3] as Long
      val frameAt = pigeonVar_list[4] as Long
      val connected = pigeonVar_list[5] as Boolean
      val stale = pigeonVar_list[6] as Boolean
      val errorCode = pigeonVar_list[7] as String?
      val desktopName = pigeonVar_list[8] as String?
      val securityType = pigeonVar_list[9] as Long?
      val protocolVersion = pigeonVar_list[10] as String?
      val extendedClipboard = pigeonVar_list[11] as Boolean?
      val hidden = pigeonVar_list[12] as Boolean?
      return ScreenInfo(textureId, width, height, generation, frameAt, connected, stale, errorCode, desktopName, securityType, protocolVersion, extendedClipboard, hidden)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      textureId,
      width,
      height,
      generation,
      frameAt,
      connected,
      stale,
      errorCode,
      desktopName,
      securityType,
      protocolVersion,
      extendedClipboard,
      hidden,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ScreenInfo
    return TvApiPigeonUtils.deepEquals(this.textureId, other.textureId) && TvApiPigeonUtils.deepEquals(this.width, other.width) && TvApiPigeonUtils.deepEquals(this.height, other.height) && TvApiPigeonUtils.deepEquals(this.generation, other.generation) && TvApiPigeonUtils.deepEquals(this.frameAt, other.frameAt) && TvApiPigeonUtils.deepEquals(this.connected, other.connected) && TvApiPigeonUtils.deepEquals(this.stale, other.stale) && TvApiPigeonUtils.deepEquals(this.errorCode, other.errorCode) && TvApiPigeonUtils.deepEquals(this.desktopName, other.desktopName) && TvApiPigeonUtils.deepEquals(this.securityType, other.securityType) && TvApiPigeonUtils.deepEquals(this.protocolVersion, other.protocolVersion) && TvApiPigeonUtils.deepEquals(this.extendedClipboard, other.extendedClipboard) && TvApiPigeonUtils.deepEquals(this.hidden, other.hidden)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.textureId)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.width)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.height)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.generation)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.frameAt)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.connected)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.stale)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.desktopName)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.securityType)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.protocolVersion)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.extendedClipboard)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.hidden)
    return result
  }
  override fun toString(): String {
    return "ScreenInfo(textureId=$textureId, width=$width, height=$height, generation=$generation, frameAt=$frameAt, connected=$connected, stale=$stale, errorCode=$errorCode, desktopName=$desktopName, securityType=$securityType, protocolVersion=$protocolVersion, extendedClipboard=$extendedClipboard, hidden=$hidden)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SessionSnapshot (
  val deviceId: String? = null,
  val sessionId: Long,
  val power: String? = null,
  val currentInput: String? = null,
  val currentApp: String? = null,
  val volume: Long? = null,
  val volumeMax: Long? = null,
  val muted: Boolean? = null,
  val model: String? = null,
  val firmware: String? = null,
  val remoteVersion: String? = null,
  val mac: String? = null,
  val editor: EditorInfo? = null,
  val screen: ScreenInfo,
  val transports: List<TransportInfo>,
  val capabilities: List<CapabilityInfo>,
  val buttons: List<TvButton>,
  val inputs: List<TvInput>,
  val apps: List<TvApplication>,
  val voiceState: String,
  val pairingState: String,
  val connectionStage: String,
  val macroId: String? = null,
  val macroStep: Long? = null,
  val errorCode: String? = null,
  val sequence: Long? = null,
  val networkPermissionGranted: Boolean? = null,
  val volumeMin: Long? = null,
  val volumeContext: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SessionSnapshot {
      val deviceId = pigeonVar_list[0] as String?
      val sessionId = pigeonVar_list[1] as Long
      val power = pigeonVar_list[2] as String?
      val currentInput = pigeonVar_list[3] as String?
      val currentApp = pigeonVar_list[4] as String?
      val volume = pigeonVar_list[5] as Long?
      val volumeMax = pigeonVar_list[6] as Long?
      val muted = pigeonVar_list[7] as Boolean?
      val model = pigeonVar_list[8] as String?
      val firmware = pigeonVar_list[9] as String?
      val remoteVersion = pigeonVar_list[10] as String?
      val mac = pigeonVar_list[11] as String?
      val editor = pigeonVar_list[12] as EditorInfo?
      val screen = pigeonVar_list[13] as ScreenInfo
      val transports = pigeonVar_list[14] as List<TransportInfo>
      val capabilities = pigeonVar_list[15] as List<CapabilityInfo>
      val buttons = pigeonVar_list[16] as List<TvButton>
      val inputs = pigeonVar_list[17] as List<TvInput>
      val apps = pigeonVar_list[18] as List<TvApplication>
      val voiceState = pigeonVar_list[19] as String
      val pairingState = pigeonVar_list[20] as String
      val connectionStage = pigeonVar_list[21] as String
      val macroId = pigeonVar_list[22] as String?
      val macroStep = pigeonVar_list[23] as Long?
      val errorCode = pigeonVar_list[24] as String?
      val sequence = pigeonVar_list[25] as Long?
      val networkPermissionGranted = pigeonVar_list[26] as Boolean?
      val volumeMin = pigeonVar_list[27] as Long?
      val volumeContext = pigeonVar_list[28] as String?
      return SessionSnapshot(deviceId, sessionId, power, currentInput, currentApp, volume, volumeMax, muted, model, firmware, remoteVersion, mac, editor, screen, transports, capabilities, buttons, inputs, apps, voiceState, pairingState, connectionStage, macroId, macroStep, errorCode, sequence, networkPermissionGranted, volumeMin, volumeContext)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      sessionId,
      power,
      currentInput,
      currentApp,
      volume,
      volumeMax,
      muted,
      model,
      firmware,
      remoteVersion,
      mac,
      editor,
      screen,
      transports,
      capabilities,
      buttons,
      inputs,
      apps,
      voiceState,
      pairingState,
      connectionStage,
      macroId,
      macroStep,
      errorCode,
      sequence,
      networkPermissionGranted,
      volumeMin,
      volumeContext,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SessionSnapshot
    return TvApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && TvApiPigeonUtils.deepEquals(this.sessionId, other.sessionId) && TvApiPigeonUtils.deepEquals(this.power, other.power) && TvApiPigeonUtils.deepEquals(this.currentInput, other.currentInput) && TvApiPigeonUtils.deepEquals(this.currentApp, other.currentApp) && TvApiPigeonUtils.deepEquals(this.volume, other.volume) && TvApiPigeonUtils.deepEquals(this.volumeMax, other.volumeMax) && TvApiPigeonUtils.deepEquals(this.muted, other.muted) && TvApiPigeonUtils.deepEquals(this.model, other.model) && TvApiPigeonUtils.deepEquals(this.firmware, other.firmware) && TvApiPigeonUtils.deepEquals(this.remoteVersion, other.remoteVersion) && TvApiPigeonUtils.deepEquals(this.mac, other.mac) && TvApiPigeonUtils.deepEquals(this.editor, other.editor) && TvApiPigeonUtils.deepEquals(this.screen, other.screen) && TvApiPigeonUtils.deepEquals(this.transports, other.transports) && TvApiPigeonUtils.deepEquals(this.capabilities, other.capabilities) && TvApiPigeonUtils.deepEquals(this.buttons, other.buttons) && TvApiPigeonUtils.deepEquals(this.inputs, other.inputs) && TvApiPigeonUtils.deepEquals(this.apps, other.apps) && TvApiPigeonUtils.deepEquals(this.voiceState, other.voiceState) && TvApiPigeonUtils.deepEquals(this.pairingState, other.pairingState) && TvApiPigeonUtils.deepEquals(this.connectionStage, other.connectionStage) && TvApiPigeonUtils.deepEquals(this.macroId, other.macroId) && TvApiPigeonUtils.deepEquals(this.macroStep, other.macroStep) && TvApiPigeonUtils.deepEquals(this.errorCode, other.errorCode) && TvApiPigeonUtils.deepEquals(this.sequence, other.sequence) && TvApiPigeonUtils.deepEquals(this.networkPermissionGranted, other.networkPermissionGranted) && TvApiPigeonUtils.deepEquals(this.volumeMin, other.volumeMin) && TvApiPigeonUtils.deepEquals(this.volumeContext, other.volumeContext)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.power)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.currentInput)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.currentApp)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.volume)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.volumeMax)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.muted)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.model)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.firmware)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.remoteVersion)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.mac)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.editor)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.screen)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.transports)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.capabilities)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.buttons)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.inputs)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.apps)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.voiceState)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.pairingState)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.connectionStage)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.macroId)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.macroStep)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.sequence)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.networkPermissionGranted)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.volumeMin)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.volumeContext)
    return result
  }
  override fun toString(): String {
    return "SessionSnapshot(deviceId=$deviceId, sessionId=$sessionId, power=$power, currentInput=$currentInput, currentApp=$currentApp, volume=$volume, volumeMax=$volumeMax, muted=$muted, model=$model, firmware=$firmware, remoteVersion=$remoteVersion, mac=$mac, editor=$editor, screen=$screen, transports=$transports, capabilities=$capabilities, buttons=$buttons, inputs=$inputs, apps=$apps, voiceState=$voiceState, pairingState=$pairingState, connectionStage=$connectionStage, macroId=$macroId, macroStep=$macroStep, errorCode=$errorCode, sequence=$sequence, networkPermissionGranted=$networkPermissionGranted, volumeMin=$volumeMin, volumeContext=$volumeContext)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TvCommand (
  val deviceId: String,
  val sessionId: Long,
  val kind: CommandKind,
  val code: Long? = null,
  val value: String? = null,
  val number: Long? = null,
  val pressId: String? = null,
  val editorRevision: Long? = null,
  val replaceText: Boolean,
  val userConfirmed: Boolean,
  val privateText: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TvCommand {
      val deviceId = pigeonVar_list[0] as String
      val sessionId = pigeonVar_list[1] as Long
      val kind = pigeonVar_list[2] as CommandKind
      val code = pigeonVar_list[3] as Long?
      val value = pigeonVar_list[4] as String?
      val number = pigeonVar_list[5] as Long?
      val pressId = pigeonVar_list[6] as String?
      val editorRevision = pigeonVar_list[7] as Long?
      val replaceText = pigeonVar_list[8] as Boolean
      val userConfirmed = pigeonVar_list[9] as Boolean
      val privateText = pigeonVar_list[10] as Boolean
      return TvCommand(deviceId, sessionId, kind, code, value, number, pressId, editorRevision, replaceText, userConfirmed, privateText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      sessionId,
      kind,
      code,
      value,
      number,
      pressId,
      editorRevision,
      replaceText,
      userConfirmed,
      privateText,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TvCommand
    return TvApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && TvApiPigeonUtils.deepEquals(this.sessionId, other.sessionId) && TvApiPigeonUtils.deepEquals(this.kind, other.kind) && TvApiPigeonUtils.deepEquals(this.code, other.code) && TvApiPigeonUtils.deepEquals(this.value, other.value) && TvApiPigeonUtils.deepEquals(this.number, other.number) && TvApiPigeonUtils.deepEquals(this.pressId, other.pressId) && TvApiPigeonUtils.deepEquals(this.editorRevision, other.editorRevision) && TvApiPigeonUtils.deepEquals(this.replaceText, other.replaceText) && TvApiPigeonUtils.deepEquals(this.userConfirmed, other.userConfirmed) && TvApiPigeonUtils.deepEquals(this.privateText, other.privateText)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.kind)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.code)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.value)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.number)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.pressId)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.editorRevision)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.replaceText)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.userConfirmed)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.privateText)
    return result
  }
  override fun toString(): String {
    return "TvCommand(deviceId=$deviceId, sessionId=$sessionId, kind=$kind, code=$code, value=$value, number=$number, pressId=$pressId, editorRevision=$editorRevision, replaceText=$replaceText, userConfirmed=$userConfirmed, privateText=$privateText)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CommandOutcome (
  val delivery: Delivery,
  val transport: String? = null,
  val errorCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CommandOutcome {
      val delivery = pigeonVar_list[0] as Delivery
      val transport = pigeonVar_list[1] as String?
      val errorCode = pigeonVar_list[2] as String?
      return CommandOutcome(delivery, transport, errorCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      delivery,
      transport,
      errorCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CommandOutcome
    return TvApiPigeonUtils.deepEquals(this.delivery, other.delivery) && TvApiPigeonUtils.deepEquals(this.transport, other.transport) && TvApiPigeonUtils.deepEquals(this.errorCode, other.errorCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TvApiPigeonUtils.deepHash(this.delivery)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.transport)
    result = 31 * result + TvApiPigeonUtils.deepHash(this.errorCode)
    return result
  }
  override fun toString(): String {
    return "CommandOutcome(delivery=$delivery, transport=$transport, errorCode=$errorCode)"
  }
}
private open class TvApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CommandKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          Availability.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          Delivery.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MacroAction.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MacroStep.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TvMacro.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TvProfile.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TvCredentials.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DiscoveredTv.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TvButton.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TvInput.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TvApplication.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CapabilityInfo.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TransportInfo.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EditorInfo.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScreenInfo.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SessionSnapshot.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TvCommand.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CommandOutcome.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CommandKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is Availability -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is Delivery -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is MacroAction -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is MacroStep -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is TvMacro -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is TvProfile -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is TvCredentials -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is DiscoveredTv -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is TvButton -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is TvInput -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is TvApplication -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is CapabilityInfo -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is TransportInfo -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is EditorInfo -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is ScreenInfo -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is SessionSnapshot -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is TvCommand -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is CommandOutcome -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TvHostApi {
  suspend fun profiles(): List<TvProfile>
  suspend fun saveProfile(profile: TvProfile, credentials: TvCredentials?): TvProfile
  suspend fun forget(deviceId: String)
  suspend fun discover(): List<DiscoveredTv>
  suspend fun requestNetworkPermission(): Boolean
  suspend fun networkPermissionAllowed(): Boolean
  suspend fun openSettings()
  suspend fun connect(deviceId: String): SessionSnapshot
  suspend fun disconnect(deviceId: String, sessionId: Long)
  suspend fun pairRemote(deviceId: String)
  suspend fun submitPairingCode(deviceId: String, sessionId: Long, code: String)
  suspend fun cancelPairing(deviceId: String, sessionId: Long)
  suspend fun registerSony(deviceId: String, sessionId: Long, pin: String?): Boolean
  suspend fun applicationIcon(deviceId: String, sessionId: Long, appId: String): ByteArray?
  suspend fun execute(command: TvCommand): CommandOutcome
  suspend fun startScreen(deviceId: String, sessionId: Long): ScreenInfo
  suspend fun stopScreen(deviceId: String, sessionId: Long)
  suspend fun screenDetail(deviceId: String, sessionId: Long, fullResolution: Boolean)
  suspend fun pointer(x: Long, y: Long, buttons: Long, generation: Long)
  suspend fun screenshot(deviceId: String, sessionId: Long): String
  suspend fun startVoice(deviceId: String, sessionId: Long)
  suspend fun stopVoice(deviceId: String, sessionId: Long)
  suspend fun refresh(deviceId: String, sessionId: Long): SessionSnapshot
  suspend fun reconnectTransport(deviceId: String, sessionId: Long, transport: String)
  suspend fun diagnosticReport(deviceId: String, sessionId: Long): String
  suspend fun runMacro(deviceId: String, sessionId: Long, macroId: String)
  suspend fun stopMacro(deviceId: String, sessionId: Long)

  companion object {
    /** The codec used by TvHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      TvApiPigeonCodec()
    }
    /** Sets up an instance of `TvHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TvHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.profiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.profiles())
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.saveProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileArg = args[0] as TvProfile
            val credentialsArg = args[1] as TvCredentials?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.saveProfile(profileArg, credentialsArg))
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.forget$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.forget(deviceIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.discover$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.discover())
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.requestNetworkPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestNetworkPermission())
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.networkPermissionAllowed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.networkPermissionAllowed())
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.openSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.openSettings()
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.connect(deviceIdArg))
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.disconnect(deviceIdArg, sessionIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.pairRemote$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.pairRemote(deviceIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.submitPairingCode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            val codeArg = args[2] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.submitPairingCode(deviceIdArg, sessionIdArg, codeArg)
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.cancelPairing$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.cancelPairing(deviceIdArg, sessionIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.registerSony$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            val pinArg = args[2] as String?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.registerSony(deviceIdArg, sessionIdArg, pinArg))
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.applicationIcon$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            val appIdArg = args[2] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.applicationIcon(deviceIdArg, sessionIdArg, appIdArg))
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.execute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val commandArg = args[0] as TvCommand
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.execute(commandArg))
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.startScreen$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.startScreen(deviceIdArg, sessionIdArg))
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.stopScreen$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.stopScreen(deviceIdArg, sessionIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.screenDetail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            val fullResolutionArg = args[2] as Boolean
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.screenDetail(deviceIdArg, sessionIdArg, fullResolutionArg)
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.pointer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val xArg = args[0] as Long
            val yArg = args[1] as Long
            val buttonsArg = args[2] as Long
            val generationArg = args[3] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.pointer(xArg, yArg, buttonsArg, generationArg)
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.screenshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.screenshot(deviceIdArg, sessionIdArg))
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.startVoice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.startVoice(deviceIdArg, sessionIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.stopVoice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.stopVoice(deviceIdArg, sessionIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.refresh$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.refresh(deviceIdArg, sessionIdArg))
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.reconnectTransport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            val transportArg = args[2] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.reconnectTransport(deviceIdArg, sessionIdArg, transportArg)
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.diagnosticReport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.diagnosticReport(deviceIdArg, sessionIdArg))
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.runMacro$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            val macroIdArg = args[2] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.runMacro(deviceIdArg, sessionIdArg, macroIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tv_vnc.TvHostApi.stopMacro$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val sessionIdArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.stopMacro(deviceIdArg, sessionIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                TvApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class TvFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TvFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      TvApiPigeonCodec()
    }
  }
  suspend fun snapshotChanged(snapshotArg: SessionSnapshot)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.tv_vnc.TvFlutterApi.snapshotChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(snapshotArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(TvApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun screenChanged(deviceIdArg: String, sessionIdArg: Long, screenArg: ScreenInfo)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.tv_vnc.TvFlutterApi.screenChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(deviceIdArg, sessionIdArg, screenArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(TvApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
