// Generated from assets/copy/en.json. Reviews: docs/reviews/copy-*.md.
abstract final class Copy {
  static String text(String key) => values[key] ?? key;
  static String format(String key, Map<String, String> arguments) => text(key)
      .replaceAllMapped(
        RegExp(r'\{([a-zA-Z]+)\}'),
        (match) => arguments[match[1]] ?? match[0]!,
      );
  static const Map<String, String> values = {
    "appTitle": "TV VNC",
    "devices": "Your TVs",
    "addTv": "Add TV",
    "discover": "Find TVs",
    "manual": "Enter address",
    "noDevices": "Add a TV to get started.",
    "discoveryEmpty":
        "No TVs found. Check that your phone and TV are on the same network.",
    "name": "TV name",
    "address": "TV address",
    "addressHint": "IP address or local hostname",
    "save": "Save",
    "cancel": "Cancel",
    "connect": "Connect",
    "disconnect": "Disconnect",
    "edit": "Edit",
    "forget": "Forget TV",
    "forgetTitle": "Forget this TV?",
    "forgetBody": "Saved settings and any pairing for this TV will be removed from this phone. Add the TV again to reconnect.",
    "remove": "Forget",
    "remote": "Remote",
    "allButtons": "All buttons",
    "touchpad": "Touchpad",
    "directTouch": "Direct touch",
    "keyboard": "Keyboard",
    "apps": "Apps",
    "inputs": "Inputs",
    "diagnostics": "Diagnostics",
    "settings": "Settings",
    "power": "Power",
    "powerOn": "Turn on",
    "powerOff": "Turn off",
    "powerToggle": "Turn on or off",
    "up": "Up",
    "down": "Down",
    "left": "Left",
    "right": "Right",
    "ok": "OK",
    "back": "Back",
    "home": "Home",
    "options": "Options",
    "input": "Input",
    "guide": "Guide",
    "info": "Info",
    "volumeUp": "Volume up",
    "volumeDown": "Volume down",
    "mute": "Mute",
    "unmute": "Unmute",
    "channelUp": "Channel up",
    "channelDown": "Channel down",
    "rewind": "Rewind",
    "playPause": "Play or pause",
    "play": "Play",
    "pause": "Pause",
    "stop": "Stop",
    "previous": "Previous",
    "next": "Next",
    "fastForward": "Fast-forward",
    "voice": "Voice",
    "holdToSpeak": "Hold to speak",
    "startVoice": "Start voice input",
    "stopVoice": "Stop voice input",
    "voiceStarting": "Starting voice input…",
    "listening": "Listening…",
    "voiceNotReady":
        "Voice input did not start. Check the TV for a search or setup screen.",
    "pairRemote": "Pair with your TV",
    "pairingCode": "Pairing code",
    "pair": "Pair",
    "pairingWaiting": "Enter the code shown on your TV.",
    "pairingRequired": "Pair with your TV to use these controls.",
    "sonyKey": "Sony pre-shared key",
    "vncPassword": "VNC password",
    "vncPort": "VNC port",
    "remotePort": "Remote service port",
    "pairingPort": "Pairing port",
    "mac": "Network MAC address",
    "screen": "Screen",
    "showScreen": "Show screen",
    "hideScreen": "Hide screen",
    "fullScreen": "Full screen",
    "exitFullScreen": "Exit full screen",
    "fit": "Fit",
    "actualSize": "Actual size",
    "zoomIn": "Zoom in",
    "zoomOut": "Zoom out",
    "screenshot": "Save screenshot",
    "reconnect": "Reconnect",
    "lastFrame": "Not live — last image received",
    "screenUnavailable":
        "Screen sharing is unavailable. Try the remote controls.",
    "screenshotSaved": "Screenshot saved on this phone.",
    "compose": "Compose",
    "liveEdit": "Live edit",
    "closeKeyboard": "Leave Keyboard",
    "leaveKeyboardTitle": "Leave with an unconfirmed edit?",
    "leaveKeyboardBody": "The TV has not confirmed your last edit. Leaving will not send it again.",
    "resizeScreen": "Drag to change screen height",
    "screenSize": "Screen height",
    "screenHeightValue": "{percent}%",
    "screenControls": "Screen options",
    "editingKeys": "Editing keys",
    "liveEditingBody": "These keys change the text above and on the TV. Enter sends your text, then presses Enter on the TV.",
    "pausedEditingBody": "Live edit is paused, so your text is not being sent. Select Live edit to load the TV’s text, replacing what is here.",
    "cursorLeft": "Move cursor left",
    "cursorRight": "Move cursor right",
    "textHint": "Type or paste text",
    "paste": "Paste",
    "send": "Send",
    "enter": "Enter",
    "backspace": "Backspace",
    "delete": "Delete",
    "privateText": "Private text",
    "clear": "Clear",
    "editorChanged":
        "The TV text field changed. Switch to Live edit again to continue.",
    "noEditor": "Select a text field on the TV first.",
    "textUnconfirmed": "Text was sent, but the TV did not confirm it. Check the TV before sending again.",
    "search": "Search",
    "favorites": "Favorites",
    "recent": "Recent",
    "favorite": "Add to favorites",
    "unfavorite": "Remove from favorites",
    "noApps": "No app list is available yet. Connect or refresh to check.",
    "noInputs": "No input list is available yet. Connect or refresh to check.",
    "refresh": "Refresh",
    "openLink": "Open app link",
    "appLink": "App link",
    "launch": "Launch",
    "connected": "Connected",
    "connecting": "Connecting…",
    "disconnected": "Not connected",
    "unknown": "Unknown",
    "needsSetup": "Needs setup",
    "permissionRequired": "Permission required",
    "unavailable": "Temporarily unavailable",
    "unsupported": "Not supported",
    "ready": "Ready",
    "tv": "TV",
    "on": "On",
    "standby": "Standby",
    "waking": "Waking TV…",
    "currentInput": "Current input",
    "currentApp": "Current app",
    "volume": "Volume",
    "muted": "Muted",
    "yes": "Yes",
    "no": "No",
    "androidRemote": "Android TV Remote",
    "sonyApi": "Sony controls",
    "vnc": "VNC",
    "latency": "Response time",
    "model": "Model",
    "firmware": "Software version",
    "serviceVersion": "Remote service version",
    "capabilities": "Detected capabilities",
    "errors": "Service errors",
    "copyReport": "Copy diagnostic report",
    "reportCopied": "Diagnostic report copied.",
    "testConnections": "Test connections",
    "refreshCapabilities": "Refresh capabilities",
    "reboot": "Restart TV",
    "rebootTitle": "Restart this TV?",
    "rebootBody":
        "The TV will turn off and start again. Anything playing will stop.",
    "restart": "Restart",
    "customize": "Customize remote",
    "resetLayout": "Reset layout",
    "moveUp": "Move up",
    "moveDown": "Move down",
    "hold": "Press and hold",
    "release": "Release",
    "macros": "Shortcuts",
    "addMacro": "Add shortcut",
    "shortcutName": "Shortcut name",
    "steps": "Steps",
    "addStep": "Add step",
    "run": "Run",
    "stopShortcut": "Stop shortcut",
    "wakeStep": "Wake TV",
    "homeStep": "Go Home",
    "inputStep": "Select input",
    "appStep": "Launch app",
    "waitStep": "Wait for the TV to be ready",
    "noMacros": "Create a shortcut to run a sequence of TV actions.",
    "networkChanged":
        "The phone’s network changed. Reconnecting on the new network…",
    "permissionBody":
        "Allow local network access to find and connect to your TVs.",
    "openSettings": "Open phone settings",
    "authFailed": "The TV did not accept the saved credentials. Check them and try again.",
    "pairingFailed":
        "Pairing failed. Check the code shown on your TV and try again.",
    "secureConnectionFailed":
        "TV VNC couldn’t connect securely to Android TV Remote.",
    "pairingUnavailable": "TV VNC couldn’t complete Android TV Remote pairing.",
    "pairingTimedOut":
        "Pairing timed out. Start pairing again to get a new code.",
    "identityChanged": "The TV’s security identity changed. It may have been reset, or another device may be answering. Pair again before controlling it.",
    "connectionFailed":
        "Could not connect. Check the address and local network.",
    "notSent": "The command was not sent.",
    "commandUnconfirmed":
        "The command was sent, but the TV did not confirm it.",
    "privateOnly": "Enter an address on your local network.",
    "invalidPort": "Enter a port from 1 to 65535.",
    "invalidMac": "Enter the TV’s network MAC address.",
    "classicVnc": "Classic VNC uses only the beginning of the password and does not encrypt the screen connection. A longer password does not add protection.",
    "noAudioSaved":
        "Microphone audio is sent to the TV. This app does not save it.",
    "captureApproval": "Screen sharing needs approval on the TV.",
    "light": "Light",
    "dark": "Dark",
    "systemTheme": "Use phone theme",
    "advertised": "Available to try — not tested yet",
    "keyCode": "Android key code",
    "sendKey": "Send key code",
    "androidStarting": "Waiting for the TV to start up…",
    "tvResponding": "Contacting the TV…",
    "screenConnecting": "Connecting the TV screen…",
    "remoteConnecting": "Connecting remote controls…",
    "micPermission": "Microphone access is allowed. Hold to speak again.",
    "microphoneUnavailable": "The phone’s microphone is unavailable. Check this app’s microphone permission in phone settings.",
    "pointerTitle": "Enable direct touch?",
    "pointerBody": "Seeing the TV screen here does not mean taps will work. Turn this on, then watch the TV to check that your taps land where you expect.",
    "enable": "Enable",
    "holdUnavailable": "Press and hold is not available through the controls connected to this TV.",
    "runButtonTitle": "Send this TV command?",
    "runButtonBody": "This command may stop playback or change TV settings. Check the command name before sending.",
    "tvClipboard": "Copy to TV clipboard",
    "tvClipboardBody": "This puts your text on the TV clipboard. It does not paste the text into a text field on the TV.",
    "commandTimeout": "The TV did not confirm this action in time. Check the TV before trying again.",
    "shortcutFailed": "The shortcut stopped because a step could not be confirmed. Earlier steps may have already run. Check the TV.",
    "networkMacHelp": "Use the TV’s Wi-Fi or Ethernet MAC address, not its Bluetooth address.",
    "screenPointer": "Direct touch",
    "sonyIrcc": "Sony remote buttons",
    "appCatalog": "App list",
    "nativeText": "Text entry on the TV",
    "wakeOnLan": "Wake-on-LAN",
    "powerState": "Power status",
    "sonyPin": "Sony registration PIN",
    "registerSony": "Register Sony controls",
    "sonyPinWaiting": "Enter the PIN shown on this TV.",
    "removeSavedSecret": "Remove saved credential",
    "anyButtons": "All buttons",
    "localNetwork": "Local network",
    "secretsSaved": "Credentials are encrypted on this phone and used only to connect to this TV.",
    "vncInput": "Key input over VNC",
    "droidConfirmed": "This TV runs droidVNC-NG",
    "droidShortcuts": "Home, Back and volume use droidVNC-NG’s default shortcuts. If those were changed in droidVNC-NG, these buttons may not work as expected.",
    "confirmInput": "Direct touch verified on this TV",
    "sendClipboardPaste": "Paste on the TV",
    "selectStep": "Choose an action",
    "screenHidden": "Screen hidden. Remote controls remain available.",
    "privateDraft":
        "Private text is cleared when you leave the Keyboard or switch TVs.",
    "powerOffFirst": "Turn the TV on before sending other controls.",
    "standbyIntent": "The app will not reconnect until you turn the TV on here, even if it is turned on another way.",
    "notConnected":
        "Not connected to this TV. Choose Connect to send controls.",
    "notCheckedYet": "Not checked yet",
    "tvEditingKeys": "TV editing keys",
    "tvEditingBody": "These keys act on the TV, not the draft above.",
    "tvBackspace": "Backspace on TV",
    "tvDelete": "Delete on TV",
    "tvCursorLeft": "Move cursor left on TV",
    "tvCursorRight": "Move cursor right on TV",
    "tvEnter": "Enter on TV",
    "touchpadHelp": "Swipe to move. Tap for OK.",
    "touchpadHold": "Touch and hold for a long press of OK.",
    "noMatchingApps": "No apps match this search.",
    "noFavorites": "No favorite apps yet. Choose Add to favorites on an app in the Apps list.",
    "noRecentApps": "No recently launched apps.",
    "shortcutRemoved": "Shortcut deleted.",
    "undo": "Undo",
    "sonyRegistrationTitle": "Register Sony controls?",
    "sonyRegistrationBody": "Registration also asks the TV to turn on Wake-on-LAN. Depending on the TV, this may change standby settings. Check the TV’s settings after registering.",
    "storageFailed": "The phone could not securely read or save TV settings. Check available storage and restart the app.",
    "controlUnavailable": "No connected service can send this control right now. Check pairing and connection status in Diagnostics.",
    "timeoutFailure": "The TV did not respond in time.",
    "connectionRefused": "The TV’s control service refused the connection. Check that the service is running and the port is correct.",
    "addressUnresolved": "The TV address could not be found. Check the address, or enter the TV’s local IP address.",
    "networkRouteUnavailable": "The phone cannot reach this local network address. Check the Wi-Fi connection and this app’s local network permission in phone settings.",
    "screenInvalid": "The VNC service sent invalid screen data. Reconnect or check the service on the TV.",
    "screenTooLarge": "The VNC screen is too large for this phone to display. Lower the screen-sharing resolution on the TV.",
    "screenSurfaceFailure": "The phone could not display the TV screen. Choose Reconnect to try again.",
    "registrationUnconfirmed":
        "The TV did not confirm Sony registration. Check the TV and try again.",
    "transportUnavailable":
        "This control service is not connected. Choose Reconnect to try again.",
    "invalidLink": "Enter a valid app link.",
    "tooMuchText": "This text is too long for the connected service. Send it in shorter parts.",
    "confirmationRequired": "Confirm this action before sending it to the TV.",
    "liveScreen": "Live TV screen",
    "editShortcut": "Edit shortcut",
    "reconnectPaused": "Automatic reconnect paused",
    "shortcutDeletedNamed": "Deleted shortcut “{shortcut}”.",
    "shortcutDeletionContext": "Deletion {number} · {tv}",
    "dismiss": "Dismiss",
  };
}
