// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum CommandKind {
  key,
  keyDown,
  keyUp,
  sony,
  text,
  input,
  app,
  powerOn,
  powerOff,
  powerToggle,
  mute,
  unmute,
  volume,
  reboot,
  paste,
}

enum Availability {
  unknown,
  advertised,
  needsSetup,
  permissionRequired,
  ready,
  unavailable,
  unsupported,
}

enum Delivery { notSent, rejected, sent, confirmed, unknown, queued }

enum MacroAction { wake, home, input, app, waitForTv, key, sony }

class MacroStep {
  MacroStep({required this.action, this.value, this.timeoutSeconds = 90});

  MacroAction action;

  String? value;

  int timeoutSeconds;

  List<Object?> _toList() {
    return <Object?>[action, value, timeoutSeconds];
  }

  Object encode() {
    return _toList();
  }

  static MacroStep decode(Object result) {
    result as List<Object?>;
    return MacroStep(
      action: result[0]! as MacroAction,
      value: result[1] as String?,
      timeoutSeconds: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MacroStep || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(action, other.action) &&
        _deepEquals(value, other.value) &&
        _deepEquals(timeoutSeconds, other.timeoutSeconds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MacroStep(action: $action, value: $value, timeoutSeconds: $timeoutSeconds)';
  }
}

class TvMacro {
  TvMacro({required this.id, required this.name, required this.steps});

  String id;

  String name;

  List<MacroStep> steps;

  List<Object?> _toList() {
    return <Object?>[id, name, steps];
  }

  Object encode() {
    return _toList();
  }

  static TvMacro decode(Object result) {
    result as List<Object?>;
    return TvMacro(
      id: result[0]! as String,
      name: result[1]! as String,
      steps: (result[2]! as List<Object?>).cast<MacroStep>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TvMacro || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(name, other.name) &&
        _deepEquals(steps, other.steps);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TvMacro(id: $id, name: $name, steps: $steps)';
  }
}

class TvProfile {
  TvProfile({
    required this.id,
    required this.name,
    required this.host,
    this.vncPort = 5900,
    this.remotePort = 6466,
    this.pairingPort = 6467,
    this.mac,
    this.hasVncPassword = false,
    this.hasSonyKey = false,
    this.paired = false,
    required this.layout,
    required this.favorites,
    required this.recents,
    required this.macros,
    this.droidVnc = false,
    this.pointerVerified = false,
  });

  String id;

  String name;

  String host;

  int vncPort;

  int remotePort;

  int pairingPort;

  String? mac;

  bool hasVncPassword;

  bool hasSonyKey;

  bool paired;

  List<String> layout;

  List<String> favorites;

  List<String> recents;

  List<TvMacro> macros;

  bool droidVnc;

  bool pointerVerified;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      host,
      vncPort,
      remotePort,
      pairingPort,
      mac,
      hasVncPassword,
      hasSonyKey,
      paired,
      layout,
      favorites,
      recents,
      macros,
      droidVnc,
      pointerVerified,
    ];
  }

  Object encode() {
    return _toList();
  }

  static TvProfile decode(Object result) {
    result as List<Object?>;
    return TvProfile(
      id: result[0]! as String,
      name: result[1]! as String,
      host: result[2]! as String,
      vncPort: result[3]! as int,
      remotePort: result[4]! as int,
      pairingPort: result[5]! as int,
      mac: result[6] as String?,
      hasVncPassword: result[7]! as bool,
      hasSonyKey: result[8]! as bool,
      paired: result[9]! as bool,
      layout: (result[10]! as List<Object?>).cast<String>(),
      favorites: (result[11]! as List<Object?>).cast<String>(),
      recents: (result[12]! as List<Object?>).cast<String>(),
      macros: (result[13]! as List<Object?>).cast<TvMacro>(),
      droidVnc: result[14]! as bool,
      pointerVerified: result[15]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TvProfile || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(name, other.name) &&
        _deepEquals(host, other.host) &&
        _deepEquals(vncPort, other.vncPort) &&
        _deepEquals(remotePort, other.remotePort) &&
        _deepEquals(pairingPort, other.pairingPort) &&
        _deepEquals(mac, other.mac) &&
        _deepEquals(hasVncPassword, other.hasVncPassword) &&
        _deepEquals(hasSonyKey, other.hasSonyKey) &&
        _deepEquals(paired, other.paired) &&
        _deepEquals(layout, other.layout) &&
        _deepEquals(favorites, other.favorites) &&
        _deepEquals(recents, other.recents) &&
        _deepEquals(macros, other.macros) &&
        _deepEquals(droidVnc, other.droidVnc) &&
        _deepEquals(pointerVerified, other.pointerVerified);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TvProfile(id: $id, name: $name, host: $host, vncPort: $vncPort, remotePort: $remotePort, pairingPort: $pairingPort, mac: $mac, hasVncPassword: $hasVncPassword, hasSonyKey: $hasSonyKey, paired: $paired, layout: $layout, favorites: $favorites, recents: $recents, macros: $macros, droidVnc: $droidVnc, pointerVerified: $pointerVerified)';
  }
}

class TvCredentials {
  TvCredentials({this.vncPassword, this.sonyKey});

  String? vncPassword;

  String? sonyKey;

  List<Object?> _toList() {
    return <Object?>[vncPassword, sonyKey];
  }

  Object encode() {
    return _toList();
  }

  static TvCredentials decode(Object result) {
    result as List<Object?>;
    return TvCredentials(
      vncPassword: result[0] as String?,
      sonyKey: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TvCredentials || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(vncPassword, other.vncPassword) &&
        _deepEquals(sonyKey, other.sonyKey);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TvCredentials(vncPassword: $vncPassword, sonyKey: $sonyKey)';
  }
}

class DiscoveredTv {
  DiscoveredTv({
    required this.name,
    required this.host,
    required this.service,
    required this.port,
  });

  String name;

  String host;

  String service;

  int port;

  List<Object?> _toList() {
    return <Object?>[name, host, service, port];
  }

  Object encode() {
    return _toList();
  }

  static DiscoveredTv decode(Object result) {
    result as List<Object?>;
    return DiscoveredTv(
      name: result[0]! as String,
      host: result[1]! as String,
      service: result[2]! as String,
      port: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DiscoveredTv || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) &&
        _deepEquals(host, other.host) &&
        _deepEquals(service, other.service) &&
        _deepEquals(port, other.port);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DiscoveredTv(name: $name, host: $host, service: $service, port: $port)';
  }
}

class TvButton {
  TvButton({
    required this.id,
    required this.name,
    this.androidCode,
    this.sonyCode,
    this.canHold = false,
    this.disruptive = false,
    this.state = Availability.unknown,
  });

  String id;

  String name;

  int? androidCode;

  String? sonyCode;

  bool canHold;

  bool disruptive;

  Availability state;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      androidCode,
      sonyCode,
      canHold,
      disruptive,
      state,
    ];
  }

  Object encode() {
    return _toList();
  }

  static TvButton decode(Object result) {
    result as List<Object?>;
    return TvButton(
      id: result[0]! as String,
      name: result[1]! as String,
      androidCode: result[2] as int?,
      sonyCode: result[3] as String?,
      canHold: result[4]! as bool,
      disruptive: result[5]! as bool,
      state: result[6]! as Availability,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TvButton || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(name, other.name) &&
        _deepEquals(androidCode, other.androidCode) &&
        _deepEquals(sonyCode, other.sonyCode) &&
        _deepEquals(canHold, other.canHold) &&
        _deepEquals(disruptive, other.disruptive) &&
        _deepEquals(state, other.state);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TvButton(id: $id, name: $name, androidCode: $androidCode, sonyCode: $sonyCode, canHold: $canHold, disruptive: $disruptive, state: $state)';
  }
}

class TvInput {
  TvInput({
    required this.uri,
    required this.name,
    this.label,
    this.connected = false,
    this.selected = false,
  });

  String uri;

  String name;

  String? label;

  bool connected;

  bool selected;

  List<Object?> _toList() {
    return <Object?>[uri, name, label, connected, selected];
  }

  Object encode() {
    return _toList();
  }

  static TvInput decode(Object result) {
    result as List<Object?>;
    return TvInput(
      uri: result[0]! as String,
      name: result[1]! as String,
      label: result[2] as String?,
      connected: result[3]! as bool,
      selected: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TvInput || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uri, other.uri) &&
        _deepEquals(name, other.name) &&
        _deepEquals(label, other.label) &&
        _deepEquals(connected, other.connected) &&
        _deepEquals(selected, other.selected);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TvInput(uri: $uri, name: $name, label: $label, connected: $connected, selected: $selected)';
  }
}

class TvApplication {
  TvApplication({
    required this.id,
    required this.name,
    required this.uri,
    this.packageName,
    this.iconBytes,
  });

  String id;

  String name;

  String uri;

  String? packageName;

  Uint8List? iconBytes;

  List<Object?> _toList() {
    return <Object?>[id, name, uri, packageName, iconBytes];
  }

  Object encode() {
    return _toList();
  }

  static TvApplication decode(Object result) {
    result as List<Object?>;
    return TvApplication(
      id: result[0]! as String,
      name: result[1]! as String,
      uri: result[2]! as String,
      packageName: result[3] as String?,
      iconBytes: result[4] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TvApplication || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(name, other.name) &&
        _deepEquals(uri, other.uri) &&
        _deepEquals(packageName, other.packageName) &&
        _deepEquals(iconBytes, other.iconBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TvApplication(id: $id, name: $name, uri: $uri, packageName: $packageName, iconBytes: $iconBytes)';
  }
}

class CapabilityInfo {
  CapabilityInfo({
    required this.id,
    required this.state,
    required this.transport,
    required this.observedAt,
    this.detail,
  });

  String id;

  Availability state;

  String transport;

  int observedAt;

  String? detail;

  List<Object?> _toList() {
    return <Object?>[id, state, transport, observedAt, detail];
  }

  Object encode() {
    return _toList();
  }

  static CapabilityInfo decode(Object result) {
    result as List<Object?>;
    return CapabilityInfo(
      id: result[0]! as String,
      state: result[1]! as Availability,
      transport: result[2]! as String,
      observedAt: result[3]! as int,
      detail: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CapabilityInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(state, other.state) &&
        _deepEquals(transport, other.transport) &&
        _deepEquals(observedAt, other.observedAt) &&
        _deepEquals(detail, other.detail);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CapabilityInfo(id: $id, state: $state, transport: $transport, observedAt: $observedAt, detail: $detail)';
  }
}

class TransportInfo {
  TransportInfo({
    required this.id,
    required this.state,
    required this.observedAt,
    this.errorCode,
    this.latencyMs,
  });

  String id;

  Availability state;

  int observedAt;

  String? errorCode;

  int? latencyMs;

  List<Object?> _toList() {
    return <Object?>[id, state, observedAt, errorCode, latencyMs];
  }

  Object encode() {
    return _toList();
  }

  static TransportInfo decode(Object result) {
    result as List<Object?>;
    return TransportInfo(
      id: result[0]! as String,
      state: result[1]! as Availability,
      observedAt: result[2]! as int,
      errorCode: result[3] as String?,
      latencyMs: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TransportInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(state, other.state) &&
        _deepEquals(observedAt, other.observedAt) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(latencyMs, other.latencyMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TransportInfo(id: $id, state: $state, observedAt: $observedAt, errorCode: $errorCode, latencyMs: $latencyMs)';
  }
}

class EditorInfo {
  EditorInfo({
    required this.application,
    required this.label,
    required this.text,
    required this.start,
    required this.end,
    required this.revision,
  });

  String application;

  String label;

  String text;

  int start;

  int end;

  int revision;

  List<Object?> _toList() {
    return <Object?>[application, label, text, start, end, revision];
  }

  Object encode() {
    return _toList();
  }

  static EditorInfo decode(Object result) {
    result as List<Object?>;
    return EditorInfo(
      application: result[0]! as String,
      label: result[1]! as String,
      text: result[2]! as String,
      start: result[3]! as int,
      end: result[4]! as int,
      revision: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EditorInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(application, other.application) &&
        _deepEquals(label, other.label) &&
        _deepEquals(text, other.text) &&
        _deepEquals(start, other.start) &&
        _deepEquals(end, other.end) &&
        _deepEquals(revision, other.revision);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EditorInfo(application: $application, label: $label, text: $text, start: $start, end: $end, revision: $revision)';
  }
}

class ScreenInfo {
  ScreenInfo({
    this.textureId,
    this.width = 0,
    this.height = 0,
    this.generation = 0,
    this.frameAt = 0,
    this.connected = false,
    this.stale = true,
    this.errorCode,
    this.desktopName,
    this.securityType,
    this.protocolVersion,
    this.extendedClipboard,
    this.hidden,
  });

  int? textureId;

  int width;

  int height;

  int generation;

  int frameAt;

  bool connected;

  bool stale;

  String? errorCode;

  String? desktopName;

  int? securityType;

  String? protocolVersion;

  bool? extendedClipboard;

  bool? hidden;

  List<Object?> _toList() {
    return <Object?>[
      textureId,
      width,
      height,
      generation,
      frameAt,
      connected,
      stale,
      errorCode,
      desktopName,
      securityType,
      protocolVersion,
      extendedClipboard,
      hidden,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ScreenInfo decode(Object result) {
    result as List<Object?>;
    return ScreenInfo(
      textureId: result[0] as int?,
      width: result[1]! as int,
      height: result[2]! as int,
      generation: result[3]! as int,
      frameAt: result[4]! as int,
      connected: result[5]! as bool,
      stale: result[6]! as bool,
      errorCode: result[7] as String?,
      desktopName: result[8] as String?,
      securityType: result[9] as int?,
      protocolVersion: result[10] as String?,
      extendedClipboard: result[11] as bool?,
      hidden: result[12] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScreenInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(textureId, other.textureId) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(generation, other.generation) &&
        _deepEquals(frameAt, other.frameAt) &&
        _deepEquals(connected, other.connected) &&
        _deepEquals(stale, other.stale) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(desktopName, other.desktopName) &&
        _deepEquals(securityType, other.securityType) &&
        _deepEquals(protocolVersion, other.protocolVersion) &&
        _deepEquals(extendedClipboard, other.extendedClipboard) &&
        _deepEquals(hidden, other.hidden);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ScreenInfo(textureId: $textureId, width: $width, height: $height, generation: $generation, frameAt: $frameAt, connected: $connected, stale: $stale, errorCode: $errorCode, desktopName: $desktopName, securityType: $securityType, protocolVersion: $protocolVersion, extendedClipboard: $extendedClipboard, hidden: $hidden)';
  }
}

class SessionSnapshot {
  SessionSnapshot({
    this.deviceId,
    this.sessionId = 0,
    this.power,
    this.currentInput,
    this.currentApp,
    this.volume,
    this.volumeMax,
    this.muted,
    this.model,
    this.firmware,
    this.remoteVersion,
    this.mac,
    this.editor,
    required this.screen,
    required this.transports,
    required this.capabilities,
    required this.buttons,
    required this.inputs,
    required this.apps,
    this.voiceState = 'idle',
    this.pairingState = 'idle',
    this.connectionStage = 'disconnected',
    this.macroId,
    this.macroStep,
    this.errorCode,
    this.sequence,
    this.networkPermissionGranted,
  });

  String? deviceId;

  int sessionId;

  String? power;

  String? currentInput;

  String? currentApp;

  int? volume;

  int? volumeMax;

  bool? muted;

  String? model;

  String? firmware;

  String? remoteVersion;

  String? mac;

  EditorInfo? editor;

  ScreenInfo screen;

  List<TransportInfo> transports;

  List<CapabilityInfo> capabilities;

  List<TvButton> buttons;

  List<TvInput> inputs;

  List<TvApplication> apps;

  String voiceState;

  String pairingState;

  String connectionStage;

  String? macroId;

  int? macroStep;

  String? errorCode;

  int? sequence;

  bool? networkPermissionGranted;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      sessionId,
      power,
      currentInput,
      currentApp,
      volume,
      volumeMax,
      muted,
      model,
      firmware,
      remoteVersion,
      mac,
      editor,
      screen,
      transports,
      capabilities,
      buttons,
      inputs,
      apps,
      voiceState,
      pairingState,
      connectionStage,
      macroId,
      macroStep,
      errorCode,
      sequence,
      networkPermissionGranted,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SessionSnapshot decode(Object result) {
    result as List<Object?>;
    return SessionSnapshot(
      deviceId: result[0] as String?,
      sessionId: result[1]! as int,
      power: result[2] as String?,
      currentInput: result[3] as String?,
      currentApp: result[4] as String?,
      volume: result[5] as int?,
      volumeMax: result[6] as int?,
      muted: result[7] as bool?,
      model: result[8] as String?,
      firmware: result[9] as String?,
      remoteVersion: result[10] as String?,
      mac: result[11] as String?,
      editor: result[12] as EditorInfo?,
      screen: result[13]! as ScreenInfo,
      transports: (result[14]! as List<Object?>).cast<TransportInfo>(),
      capabilities: (result[15]! as List<Object?>).cast<CapabilityInfo>(),
      buttons: (result[16]! as List<Object?>).cast<TvButton>(),
      inputs: (result[17]! as List<Object?>).cast<TvInput>(),
      apps: (result[18]! as List<Object?>).cast<TvApplication>(),
      voiceState: result[19]! as String,
      pairingState: result[20]! as String,
      connectionStage: result[21]! as String,
      macroId: result[22] as String?,
      macroStep: result[23] as int?,
      errorCode: result[24] as String?,
      sequence: result[25] as int?,
      networkPermissionGranted: result[26] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SessionSnapshot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) &&
        _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(power, other.power) &&
        _deepEquals(currentInput, other.currentInput) &&
        _deepEquals(currentApp, other.currentApp) &&
        _deepEquals(volume, other.volume) &&
        _deepEquals(volumeMax, other.volumeMax) &&
        _deepEquals(muted, other.muted) &&
        _deepEquals(model, other.model) &&
        _deepEquals(firmware, other.firmware) &&
        _deepEquals(remoteVersion, other.remoteVersion) &&
        _deepEquals(mac, other.mac) &&
        _deepEquals(editor, other.editor) &&
        _deepEquals(screen, other.screen) &&
        _deepEquals(transports, other.transports) &&
        _deepEquals(capabilities, other.capabilities) &&
        _deepEquals(buttons, other.buttons) &&
        _deepEquals(inputs, other.inputs) &&
        _deepEquals(apps, other.apps) &&
        _deepEquals(voiceState, other.voiceState) &&
        _deepEquals(pairingState, other.pairingState) &&
        _deepEquals(connectionStage, other.connectionStage) &&
        _deepEquals(macroId, other.macroId) &&
        _deepEquals(macroStep, other.macroStep) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(sequence, other.sequence) &&
        _deepEquals(networkPermissionGranted, other.networkPermissionGranted);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SessionSnapshot(deviceId: $deviceId, sessionId: $sessionId, power: $power, currentInput: $currentInput, currentApp: $currentApp, volume: $volume, volumeMax: $volumeMax, muted: $muted, model: $model, firmware: $firmware, remoteVersion: $remoteVersion, mac: $mac, editor: $editor, screen: $screen, transports: $transports, capabilities: $capabilities, buttons: $buttons, inputs: $inputs, apps: $apps, voiceState: $voiceState, pairingState: $pairingState, connectionStage: $connectionStage, macroId: $macroId, macroStep: $macroStep, errorCode: $errorCode, sequence: $sequence, networkPermissionGranted: $networkPermissionGranted)';
  }
}

class TvCommand {
  TvCommand({
    required this.deviceId,
    required this.sessionId,
    required this.kind,
    this.code,
    this.value,
    this.number,
    this.pressId,
    this.editorRevision,
    this.replaceText = false,
    this.userConfirmed = false,
    this.privateText = false,
  });

  String deviceId;

  int sessionId;

  CommandKind kind;

  int? code;

  String? value;

  int? number;

  String? pressId;

  int? editorRevision;

  bool replaceText;

  bool userConfirmed;

  bool privateText;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      sessionId,
      kind,
      code,
      value,
      number,
      pressId,
      editorRevision,
      replaceText,
      userConfirmed,
      privateText,
    ];
  }

  Object encode() {
    return _toList();
  }

  static TvCommand decode(Object result) {
    result as List<Object?>;
    return TvCommand(
      deviceId: result[0]! as String,
      sessionId: result[1]! as int,
      kind: result[2]! as CommandKind,
      code: result[3] as int?,
      value: result[4] as String?,
      number: result[5] as int?,
      pressId: result[6] as String?,
      editorRevision: result[7] as int?,
      replaceText: result[8]! as bool,
      userConfirmed: result[9]! as bool,
      privateText: result[10]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TvCommand || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) &&
        _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(code, other.code) &&
        _deepEquals(value, other.value) &&
        _deepEquals(number, other.number) &&
        _deepEquals(pressId, other.pressId) &&
        _deepEquals(editorRevision, other.editorRevision) &&
        _deepEquals(replaceText, other.replaceText) &&
        _deepEquals(userConfirmed, other.userConfirmed) &&
        _deepEquals(privateText, other.privateText);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TvCommand(deviceId: $deviceId, sessionId: $sessionId, kind: $kind, code: $code, value: $value, number: $number, pressId: $pressId, editorRevision: $editorRevision, replaceText: $replaceText, userConfirmed: $userConfirmed, privateText: $privateText)';
  }
}

class CommandOutcome {
  CommandOutcome({required this.delivery, this.transport, this.errorCode});

  Delivery delivery;

  String? transport;

  String? errorCode;

  List<Object?> _toList() {
    return <Object?>[delivery, transport, errorCode];
  }

  Object encode() {
    return _toList();
  }

  static CommandOutcome decode(Object result) {
    result as List<Object?>;
    return CommandOutcome(
      delivery: result[0]! as Delivery,
      transport: result[1] as String?,
      errorCode: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CommandOutcome || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(delivery, other.delivery) &&
        _deepEquals(transport, other.transport) &&
        _deepEquals(errorCode, other.errorCode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CommandOutcome(delivery: $delivery, transport: $transport, errorCode: $errorCode)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is CommandKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is Availability) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is Delivery) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is MacroAction) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is MacroStep) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is TvMacro) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is TvProfile) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is TvCredentials) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is DiscoveredTv) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is TvButton) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is TvInput) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is TvApplication) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is CapabilityInfo) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is TransportInfo) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is EditorInfo) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is ScreenInfo) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is SessionSnapshot) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is TvCommand) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is CommandOutcome) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : CommandKind.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : Availability.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : Delivery.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : MacroAction.values[value];
      case 133:
        return MacroStep.decode(readValue(buffer)!);
      case 134:
        return TvMacro.decode(readValue(buffer)!);
      case 135:
        return TvProfile.decode(readValue(buffer)!);
      case 136:
        return TvCredentials.decode(readValue(buffer)!);
      case 137:
        return DiscoveredTv.decode(readValue(buffer)!);
      case 138:
        return TvButton.decode(readValue(buffer)!);
      case 139:
        return TvInput.decode(readValue(buffer)!);
      case 140:
        return TvApplication.decode(readValue(buffer)!);
      case 141:
        return CapabilityInfo.decode(readValue(buffer)!);
      case 142:
        return TransportInfo.decode(readValue(buffer)!);
      case 143:
        return EditorInfo.decode(readValue(buffer)!);
      case 144:
        return ScreenInfo.decode(readValue(buffer)!);
      case 145:
        return SessionSnapshot.decode(readValue(buffer)!);
      case 146:
        return TvCommand.decode(readValue(buffer)!);
      case 147:
        return CommandOutcome.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class TvHostApi {
  /// Constructor for [TvHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TvHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<TvProfile>> profiles() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.profiles$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<TvProfile>();
  }

  Future<TvProfile> saveProfile(
    TvProfile profile,
    TvCredentials? credentials,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.saveProfile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[profile, credentials],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as TvProfile;
  }

  Future<void> forget(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.forget$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<List<DiscoveredTv>> discover() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.discover$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<DiscoveredTv>();
  }

  Future<bool> requestNetworkPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.requestNetworkPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> networkPermissionAllowed() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.networkPermissionAllowed$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> openSettings() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.openSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<SessionSnapshot> connect(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as SessionSnapshot;
  }

  Future<void> disconnect(String deviceId, int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> pairRemote(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.pairRemote$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> submitPairingCode(
    String deviceId,
    int sessionId,
    String code,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.submitPairingCode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId, code],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancelPairing(String deviceId, int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.cancelPairing$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> registerSony(String deviceId, int sessionId, String? pin) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.registerSony$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId, pin],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<Uint8List?> applicationIcon(
    String deviceId,
    int sessionId,
    String appId,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.applicationIcon$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId, appId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as Uint8List?;
  }

  Future<CommandOutcome> execute(TvCommand command) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.execute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[command],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CommandOutcome;
  }

  Future<ScreenInfo> startScreen(String deviceId, int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.startScreen$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ScreenInfo;
  }

  Future<void> stopScreen(String deviceId, int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.stopScreen$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> screenDetail(
    String deviceId,
    int sessionId,
    bool fullResolution,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.screenDetail$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId, fullResolution],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> pointer(int x, int y, int buttons, int generation) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.pointer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[x, y, buttons, generation],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String> screenshot(String deviceId, int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.screenshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<void> startVoice(String deviceId, int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.startVoice$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stopVoice(String deviceId, int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.stopVoice$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<SessionSnapshot> refresh(String deviceId, int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.refresh$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as SessionSnapshot;
  }

  Future<void> reconnectTransport(
    String deviceId,
    int sessionId,
    String transport,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.reconnectTransport$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId, transport],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String> diagnosticReport(String deviceId, int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.diagnosticReport$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<void> runMacro(String deviceId, int sessionId, String macroId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.runMacro$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId, macroId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stopMacro(String deviceId, int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tv_vnc.TvHostApi.stopMacro$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class TvFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void snapshotChanged(SessionSnapshot snapshot);

  void screenChanged(String deviceId, int sessionId, ScreenInfo screen);

  static void setUp(
    TvFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.tv_vnc.TvFlutterApi.snapshotChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final SessionSnapshot arg_snapshot = args[0]! as SessionSnapshot;
          try {
            api.snapshotChanged(arg_snapshot);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.tv_vnc.TvFlutterApi.screenChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_deviceId = args[0]! as String;
          final int arg_sessionId = args[1]! as int;
          final ScreenInfo arg_screen = args[2]! as ScreenInfo;
          try {
            api.screenChanged(arg_deviceId, arg_sessionId, arg_screen);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
